from django.test import TestCase
from solver.models.board import Board
from solver.models.board import calc_tic_num

# Create your tests here.

class BoardTestCase(TestCase):
  def test_create_board(self):
    b = Board.objects.create()
    self.assertNotEqual(b, None)
    self.assertEqual(b.row_set.count(), 9)
  
  def test_calc_tic_num(self):
    tic_num = calc_tic_num(1,1)
    self.assertEqual(tic_num, 1)
    tic_num = calc_tic_num(1,3)
    self.assertEqual(tic_num, 1)
    tic_num = calc_tic_num(1,4)
    self.assertEqual(tic_num, 2)
    tic_num = calc_tic_num(1,6)
    self.assertEqual(tic_num, 2)
    tic_num = calc_tic_num(1,7)
    self.assertEqual(tic_num, 3)
    tic_num = calc_tic_num(1,9)
    self.assertEqual(tic_num, 3)
    tic_num = calc_tic_num(3,1)
    self.assertEqual(tic_num, 1)
    tic_num = calc_tic_num(3,3)
    self.assertEqual(tic_num, 1)
    tic_num = calc_tic_num(3,4)
    self.assertEqual(tic_num, 2)
    tic_num = calc_tic_num(3,6)
    self.assertEqual(tic_num, 2)
    tic_num = calc_tic_num(3,7)
    self.assertEqual(tic_num, 3)
    tic_num = calc_tic_num(3,9)
    self.assertEqual(tic_num, 3)
    tic_num = calc_tic_num(4,1)
    self.assertEqual(tic_num, 4)
    tic_num = calc_tic_num(4,3)
    self.assertEqual(tic_num, 4)
    tic_num = calc_tic_num(4,4)
    self.assertEqual(tic_num, 5)
    tic_num = calc_tic_num(4,6)
    self.assertEqual(tic_num, 5)
    tic_num = calc_tic_num(4,7)
    self.assertEqual(tic_num, 6)
    tic_num = calc_tic_num(4,9)
    self.assertEqual(tic_num, 6)
    tic_num = calc_tic_num(6,1)
    self.assertEqual(tic_num, 4)
    tic_num = calc_tic_num(6,3)
    self.assertEqual(tic_num, 4)
    tic_num = calc_tic_num(6,4)
    self.assertEqual(tic_num, 5)
    tic_num = calc_tic_num(6,6)
    self.assertEqual(tic_num, 5)
    tic_num = calc_tic_num(6,7)
    self.assertEqual(tic_num, 6)
    tic_num = calc_tic_num(6,9)
    self.assertEqual(tic_num, 6)
    tic_num = calc_tic_num(7,1)
    self.assertEqual(tic_num, 7)
    tic_num = calc_tic_num(7,3)
    self.assertEqual(tic_num, 7)
    tic_num = calc_tic_num(7,4)
    self.assertEqual(tic_num, 8)
    tic_num = calc_tic_num(7,6)
    self.assertEqual(tic_num, 8)
    tic_num = calc_tic_num(7,7)
    self.assertEqual(tic_num, 9)
    tic_num = calc_tic_num(7,9)
    self.assertEqual(tic_num, 9)
    tic_num = calc_tic_num(9,1)
    self.assertEqual(tic_num, 7)
    tic_num = calc_tic_num(9,3)
    self.assertEqual(tic_num, 7)
    tic_num = calc_tic_num(9,4)
    self.assertEqual(tic_num, 8)
    tic_num = calc_tic_num(9,6)
    self.assertEqual(tic_num, 8)
    tic_num = calc_tic_num(9,7)
    self.assertEqual(tic_num, 9)
    tic_num = calc_tic_num(9,9)
    self.assertEqual(tic_num, 9)
    
